### ISSUE TITLE
Circular imports in article.py and infobox.py

### ISSUE THREAD

**Issue by alvaromorales** [fakedrake/WikipediaBase#33]
`infobox.Infobox` is not imported in `article.py`.

```python
>>> from wikipediabase.article import Article
>>> Article("foo title").infobox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/csail.mit.edu/u/a/alvarom/pywikipediabase/wikipediabase/article.py", line 45, in infobox
    self.ibox = Infobox(self.title, fetcher=self.fetcher)
NameError: global name 'Infobox' is not defined
```

The error can't be fixed by adding `from wikipediabase.infobox import Infobox` as this creates a circular import error. `infobox.py` imports `article.py` (line 8: `from wikipediabase.article import Article`).

I think that `infobox.py` should *not* import `article.py`. `Article` is only used in `Infobox.types()` to get the title.

**Comment by fakedrake** [comment]
I think I tested and fixed it. For future reference, because creating Infobox and Article objects requires some sort of IO, they are computationally expensive. For that reason and also to avoid circular dependencies the correct way to create them is via `get_{article,infobox,meta_infobox}` from util.py. This way we can efficiently cache and reuse Infobox and Article objects since they are effectively immutable.
